add README.md to describe where the source of manual exists
spotbugs/spotbugs.github.io pull request #22
Opened 2017-07-02 13:18 UTC by KengoTODA

This will close #18

2017-07-02 13:36 UTC, iloveeclipse requested changes
Looks good, but where is the link to the "how to upload the changed manual to readthedocs"?

2017-07-15 12:57 UTC, koppor commented
Reading https://docs.readthedocs.io/en/latest/getting_started.html#sign-up-and-connect-an-external-account, it seems that there is a web hook at https://github.com/spotbugs/spotbugs/settings/hooks configured. That means, the upload is done automatically on each change.

2017-07-16 00:57 UTC, KengoTODA commented
@iloveeclipse Can we merge this PR too?

2017-07-16 05:43 UTC, iloveeclipse approved these changes

2017-07-16 05:43 UTC, merged