Clarify relationship of SpotBugs to FindBugs
spotbugs/spotbugs.github.io pull request #40
Opened 2021-04-30 13:37 UTC by mernst

As noted in https://github.com/spotbugs/spotbugs.github.io/issues/24, the text "spiritual successor" is confusing.
This pull request clarifies the documentation:  SpotBugs is a fork of FindBugs.

2021-04-30 14:34 UTC, iloveeclipse requested changes
I'm not happy with that. "Fork" suggests that the original project still lives. FindBugs is dead. Spotbugsis a successor of FindBugs, a continuation, nkt a fork.

2021-04-30 16:25 UTC, mernst commented
https://github.com/spotbugs/spotbugs.github.io/issues/24#issuecomment-315666842 says "SpotBugs is a fork of FindBugs".  I added your text noting that FindBugs is dead, to avoid confusion.

2021-04-30 16:31 UTC, iloveeclipse commented
@spotbugs/everyone - WDYT?

2021-04-30 17:01 UTC, jscancella commented
I think stating it is a fork and that the previous project is dead is fine. Perhaps "abandoned" is better than "dead"? I also think we could spend ages arguing over the best words, so I would just go with what is there honestly.

2021-05-24 19:45 UTC, mernst commented
A ping on this pull request.  Can it be merged?

2021-06-24 01:50 UTC, KengoTODA commented
I used the word "fork" at https://github.com/spotbugs/spotbugs.github.io/issues/24#issuecomment-315666842 but please don't care so much about what I used. I paid less care to pick a word.

2021-06-24 04:30 UTC, iloveeclipse approved these changes
LGTM

2021-07-13 17:12 UTC, mernst commented
Another ping on this pull request.  Can it be merged?

2021-07-14 01:59 UTC, merged

2021-07-14 02:03 UTC, mernst commented
Thanks!